language: csharp
mono: none
dotnet: 2.1

env:
  global:
    - IDFY_MOCK_SERVER_VERSION=0.0.1

before_install:
  # Download, unpack and run the Idfy Mock Server
  - |
    mkdir -p idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/
    curl -L "https://github.com/idfy-io/idfy-mock-server/releases/download/v${IDFY_MOCK_SERVER_VERSION}/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip" -o "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip"
    unzip "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip" -d "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/"
    dotnet "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/Idfy.MockServer.dll" &

install:
  - dotnet restore src/

script:
  - dotnet build -c Release src/
  - dotnet test src/Idfy.SDK.Tests/Idfy.SDK.Tests.csproj
  - dotnet pack src/Idfy.SDK/ -c Release
  - dotnet pack src/Idfy.SDK/ -c Release --version-suffix ci-$TRAVIS_BUILD_NUMBER

deploy:
  # Deploy GitHub release on new version
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    on:
      tags: true
  # Push NuGet package to MyGet feed on each CI build
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push src/Idfy.SDK/bin/Release/Idfy.SDK.*ci-$TRAVIS_BUILD_NUMBER --api-key $MYGET_APIKEY --source https://www.myget.org/F/identisign/api/v2/package
